language: cpp
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - clang-3.8
      - libstdc++6
      - lib32stdc++6
      - libc6-dev
      - libc6-dev-i386
      - linux-libc-dev
      - linux-libc-dev:i386
env:
  global:
    - EMSCRIPTEN_SDK_BRANCH=incoming
    - EMSCRIPTEN_SDK_URI=https://github.com/urho3d/emscripten-sdk.git
  matrix:
    - AM_CC=clang-3.8 AM_CXX=clang++-3.8 AM_ARCH=x86 AM_TYPE=optimize
    - AM_CC=clang-3.8 AM_CXX=clang++-3.8 AM_ARCH=x64 AM_TYPE=optimize
    - AM_CC=clang-3.8 AM_CXX=clang++-3.8 AM_ARCH=x86 AM_TYPE=debug
    - AM_CC=clang-3.8 AM_CXX=clang++-3.8 AM_ARCH=x64 AM_TYPE=debug
install:
  - source ./tools/travis-download-compiler.sh
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/tools/checkout-deps.sh && cd $CHECKOUT_DIR
  - export PATH="~/.local/bin:$PATH"
  - $AM_CXX --version
script:
  - mkdir $AM_CC-$AM_ARCH-$AM_TYPE && cd $AM_CC-$AM_ARCH-$AM_TYPE
  - CC=$AM_CC CXX=$AM_CXX python ../configure.py --enable-$AM_TYPE --target-arch=$AM_ARCH
  - ambuild
  - python $CHECKOUT_DIR/tests/runtests.py .
